### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by Danieleeffe1** [meanbee/magento-estimateddelivery#9]
Goodmorning everyone.

I report a bug found.

I use OpenMage (php7.4) but the bug also shows up on magento 1.9.4.5 (php7.1)

The module does not allow you to clear the cache.

the server returns error 500

server error:

Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Mage_Core_Model_Resource_Setup::__construct(), 0 passed in /var/www/html/openmage/app/code/community/Meanbee/EstimatedDelivery/sql/meanbee_estimateddelivery_setup/mysql4-upgrade-1.3.0-1.3.1.php on line 4 and exactly 1 expected in /var/www/html/openmage/app/code/core/Mage/Core/Model/Resource/Setup.php:127\nStack trace:\n#0 /var/www/html/openmage/app/code/community/Meanbee/EstimatedDelivery/sql/meanbee_estimateddelivery_setup/mysql4-upgrade-1.3.0-1.3.1.php(4): Mage_Core_Model_Resource_Setup->__construct()\n#1 /var/www/html/openmage/app/code/core/Mage/Core/Model/Resource/Setup.php(622): include('/var/www/html/m...')\n#2 /var/www/html/openmage/app/code/core/Mage/Core/Model/Resource/Setup.php(437): Mage_Core_Model_Resource_Setup->_modifyResourceDb()\n#3 /var/www/html/openmage/app/code/core/Mage/Core/Model/Resource/Setup.php(320): Mage_Core_Model_Resource_Setup->_upg...', referer: https://openmage/index.php/admin/cache/index/key/a4b0d0bc0e8fac30e9104dbfaa06fbf7/

**Comment by Danieleeffe1** [comment]
qualcuno supporta questo modulo?
